v1.1.0

diff --git a/bin/build b/bin/build
--- a/bin/build
+++ b/bin/build
@@ -5,20 +5,37 @@ set -e
 issh2_dir="$PWD/iSSH2"
 libgit2_dir="$PWD/libgit2"
 
+ios_min_version=11.0.0
+macos_min_version=10.13.0
+
+build_macosx=true
+build_iphoneos=true
+build_iphonesimulator=true
+
+declare -a cmake_configure_opts
+
 build_and_install() {
-  if command -v xcpretty >/dev/null 2>&1; then
-    cmake --build . --target install | xcpretty
-  else
-    cmake --build . --target install
-  fi
+  local platform=$1
+  local build_dir=$2
+  local build_log=$2/build.log
+  echo -n "Building $platform..."
+  trap 'echo " failed. ($build_log)"' ERR
+  cmake --build "$build_dir" --target install >"$build_log"
+  trap - ERR
+  echo " done."
 }
 
 cmake_configure() {
-  cmake -G Xcode "$libgit2_dir" \
+  local build_dir=$1; shift
+  pushd &>/dev/null "$build_dir"
+  cmake "${cmake_configure_opts[@]}" "$libgit2_dir" \
+    -DBUILD_CLAR:BOOL=OFF \
+    -DBUILD_SHARED_LIBS:BOOL=OFF \
+    -DREGEX_BACKEND=builtin \
     -DCMAKE_C_FLAGS=-fembed-bitcode \
-    -DCMAKE_INSTALL_PREFIX="Products/\$ENV{PROJECT_NAME}\$ENV{EFFECTIVE_PLATFORM_NAME}" \
-    -DCMAKE_XCODE_ATTRIBUTE_BITCODE_ENABLED=YES \
+    -DCMAKE_INSTALL_PREFIX="Products" \
     "$@"
+  popd &>/dev/null
 }
 
 cmake_prefix() {
@@ -58,19 +75,25 @@ xcode_arch_sysroots() {
 
 build_openssl() {
   mkdir -p .build/OpenSSL
-  pushd .build/OpenSSL
+  pushd &>/dev/null .build/OpenSSL
 
-  issh2 --no-clean --platform=macosx --archs="arm64 x86_64" --min-version=10.11.0
-  mkdir -p macosx/lib
-  libtool -static -o macosx/lib/libOpenSSL.a "$issh2_dir"/openssl_macosx/lib/*.a
+  if [[ $build_macosx == true ]]; then
+    issh2 --no-clean --platform=macosx --archs="arm64 x86_64" --min-version="$macos_min_version"
+    mkdir -p macosx/lib
+    libtool -static -o macosx/lib/libOpenSSL.a "$issh2_dir"/openssl_macosx/lib/*.a
+  fi
 
-  issh2 --no-clean --platform=iphoneos --archs=arm64 --min-version=9.0.0
-  mkdir -p iphoneos/lib
-  libtool -static -o iphoneos/lib/libOpenSSL.a "$issh2_dir"/openssl_iphoneos/lib/*.a
+  if [[ $build_iphoneos == true ]]; then
+    issh2 --no-clean --platform=iphoneos --archs=arm64 --min-version="$ios_min_version"
+    mkdir -p iphoneos/lib
+    libtool -static -o iphoneos/lib/libOpenSSL.a "$issh2_dir"/openssl_iphoneos/lib/*.a
+  fi
 
-  issh2 --platform=iphonesimulator --archs="arm64 x86_64" --min-version=9.0.0
-  mkdir -p iphonesimulator/lib
-  libtool -static -o iphonesimulator/lib/libOpenSSL.a "$issh2_dir"/openssl_iphonesimulator/lib/*.a
+  if [[ $build_iphonesimulator == true ]]; then
+    issh2 --no-clean --platform=iphonesimulator --archs="arm64 x86_64" --min-version="$ios_min_version"
+    mkdir -p iphonesimulator/lib
+    libtool -static -o iphonesimulator/lib/libOpenSSL.a "$issh2_dir"/openssl_iphonesimulator/lib/*.a
+  fi
 
   rm -rf ../OpenSSL.xcframework
   xcodebuild -create-xcframework \
@@ -82,7 +105,7 @@ build_openssl() {
     -library iphonesimulator/lib/*.a \
     -headers "$issh2_dir"/openssl_iphonesimulator/include
 
-  popd
+  popd &>/dev/null
 
   rm -rf .build/libssh2.xcframework
   xcodebuild -create-xcframework \
@@ -97,91 +120,103 @@ build_openssl() {
 
 # ============================================================================ #
 
-build_libssh2() {
-  mkdir -p .build/libssh2
-  pushd .build/libssh2
-
-  issh2 --platform=macosx --archs="arm64 x86_64" --min-version=10.11.0
-  mkdir -p macosx/lib
-  libtool -static -o macosx/lib/libOpenSSL.a "$issh2_dir"/openssl_macosx/lib/*.a
-
-  issh2 --platform=iphoneos --archs=arm64 --min-version=9.0.0
-  mkdir -p iphoneos/lib
-  libtool -static -o iphoneos/lib/libOpenSSL.a "$issh2_dir"/openssl_iphoneos/lib/*.a
-
-  issh2 --platform=iphonesimulator --archs="arm64 x86_64" --min-version=9.0.0
-  mkdir -p iphonesimulator/lib
-  libtool -static -o iphonesimulator/lib/libOpenSSL.a "$issh2_dir"/openssl_iphonesimulator/lib/*.a
-
-  rm -rf ../OpenSSL.xcframework
-  xcodebuild -create-xcframework \
-    -output ../OpenSSL.xcframework \
-    -library macosx/lib/*.a \
-    -headers "$issh2_dir"/openssl_macosx/include \
-    -library iphoneos/lib/*.a \
-    -headers "$issh2_dir"/openssl_iphoneos/include \
-    -library iphonesimulator/lib/*.a \
-    -headers "$issh2_dir"/openssl_iphonesimulator/include
-
-  popd
-}
-
-# ============================================================================ #
-
 build_libgit2() {
-  mkdir -p .build/libgit2
-  pushd .build/libgit2
+  if [[ $build_macosx == true ]]; then
+    build_dir=.build/libgit2/macosx
+    configure_log=$build_dir/configure.log
+    mkdir -p "$build_dir"
 
-  # macosx
+    echo -n "Configuring macosx..."
+    trap ' failed. ($configure_log)' ERR
+    cmake_configure "$build_dir" \
+      -DCMAKE_PREFIX_PATH="$(cmake_prefix macosx)" \
+      -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" \
+      -DCMAKE_OSX_DEPLOYMENT_TARGET="$macos_min_version" \
+      -DCMAKE_OSX_SYSROOT=macosx \
+      >"$configure_log"
+    trap - ERR
+    echo " done."
 
-  cmake_configure \
-    -DCMAKE_PREFIX_PATH="$(cmake_prefix macosx)" \
-    -DBUILD_SHARED_LIBS:BOOL=OFF \
-    -DBUILD_CLAR:BOOL=OFF \
-    -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" \
-    -DCMAKE_APPLE_ARCH_SYSROOTS="$(xcode_arch_sysroots macosx arm64 x86_64)" \
-    -DCMAKE_OSX_DEPLOYMENT_TARGET=10.13.0 \
-    -DCMAKE_OSX_SYSROOT=macosx
+    build_and_install macosx "$build_dir"
+  fi
 
-  build_and_install
+  if [[ $build_iphoneos == true ]]; then
+    build_dir=.build/libgit2/iphoneos
+    configure_log=$build_dir/configure.log
+    mkdir -p "$build_dir"
 
-  # iphoneos
+    echo -n "Configuring iphoneos..."
+    trap ' failed. ($configure_log)' ERR
+    cmake_configure "$build_dir" \
+      -DCMAKE_PREFIX_PATH="$(cmake_prefix iphoneos)" \
+      -DCMAKE_C_COMPILER_WORKS:BOOL=ON \
+      -DCMAKE_OSX_ARCHITECTURES=arm64 \
+      -DCMAKE_OSX_DEPLOYMENT_TARGET="$ios_min_version" \
+      -DCMAKE_OSX_SYSROOT=iphoneos \
+      >"$configure_log"
+    trap - ERR
+    echo " done."
 
-  cmake_configure \
-    -DCMAKE_PREFIX_PATH="$(cmake_prefix iphoneos)" \
-    -DBUILD_SHARED_LIBS:BOOL=OFF \
-    -DBUILD_CLAR:BOOL=OFF \
-    -DREGEX_BACKEND=builtin \
-    -DCMAKE_OSX_ARCHITECTURES=arm64 \
-    -DCMAKE_APPLE_ARCH_SYSROOTS="$(xcode_arch_sysroots iphoneos arm64)" \
-    -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0 \
-    -DCMAKE_OSX_SYSROOT=iphoneos
+    build_and_install iphoneos "$build_dir"
+  fi
 
-  build_and_install
+  if [[ $build_iphonesimulator == true ]]; then
+    build_dir=.build/libgit2/iphonesimulator
+    configure_log=$build_dir/configure.log
+    mkdir -p "$build_dir"
 
-  # iphonesimulator
+    echo -n "Configuring iphonesimulator..."
+    trap ' failed. ($configure_log)' ERR
+    cmake_configure "$build_dir" \
+      -DCMAKE_PREFIX_PATH:PATH="$(cmake_prefix iphonesimulator)" \
+      -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" \
+      -DCMAKE_OSX_DEPLOYMENT_TARGET="$ios_min_version" \
+      -DCMAKE_OSX_SYSROOT=iphonesimulator \
+      >"$configure_log"
+    trap - ERR
+    echo " done."
 
-  cmake_configure \
-    -DCMAKE_PREFIX_PATH:PATH="$(cmake_prefix iphonesimulator)" \
-    -DBUILD_SHARED_LIBS:BOOL=OFF \
-    -DBUILD_CLAR:BOOL=OFF \
-    -DREGEX_BACKEND=builtin \
-    -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" \
-    -DCMAKE_APPLE_ARCH_SYSROOTS="$(xcode_arch_sysroots iphonesimulator arm64 x86_64)" \
-    -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0 \
-    -DCMAKE_OSX_SYSROOT=iphonesimulator
-
-  build_and_install
+    build_and_install iphonesimulator "$build_dir"
+  fi
 
   # build xcframework
 
-  create_xcframework ../libgit2.xcframework Products/*
-
-  popd
+  create_xcframework .build/libgit2.xcframework .build/libgit2/*/Products
 }
 
 # ============================================================================ #
 
+for opt; do
+  case $opt in
+    --macosx)
+      build_macosx=true
+      build_iphoneos=false
+      build_iphonesimulator=false
+      ;;
+    --iphoneos)
+      build_macosx=false
+      build_iphoneos=true
+      build_iphonesimulator=false
+      ;;
+    --iphonesimulator)
+      build_macosx=false
+      build_iphoneos=false
+      build_iphonesimulator=true
+      ;;
+    *)
+      echo >&2 "Unknown option '$opt'"
+      exit 1
+      ;;
+  esac
+done
+
 mkdir -p .build
+
 build_openssl
+
+if ninja_path="$(command -v ninja)"; then
+  echo "Configuring CMake to use Ninja (found at path $ninja_path)"
+  cmake_configure_opts+=(-G Ninja)
+fi
+
 build_libgit2
